name: Train
inputs:
- {name: curl options, type: string, default: '--location', description: 'Additional options given to the curl bprogram. See https://curl.haxx.se/docs/manpage.html'}
implementation:
  container:
    # image: curlimages/curl  # Sets a non-root user which cannot write to mounted volumes. See https://github.com/curl/curl-docker/issues/22
    image: kedarwaghmode/kubeflow-demo:latest
    command:
    - python
    - src/train.py
    - inputValue: curl options
    - outputPath: Data
